### PR TITLE
cremona fixes

### LINKED ISSUE #10: Book with a single author fetches empty authors
Example: EVIDENSBAS FÖR VÅRDENS ARKITEK

Has one author but when fetching the book with cremona, it returns an empty list.

### PR DESCRIPTION
**Pull request by emilsvennesson**
* formatting
* adds publisher
* adds edition
* fixes #10

### CODE REVIEW

**Review by sundstromalbin — COMMENTED** [review]
lgtm

File: cremona/src/Book.ts [hunk 1]
```diff
@@ -1,43 +1,58 @@
...
+    if (props['attributes'][1357] !== undefined) {
+      this.authors = props['attributes'][1357]['sv']
+        .replace(', ', ',')
+        .split(',');
+    } else if (props['attributes'][2513] !== undefined) {
+      this.authors = props['attributes'][2513]['sv']
+        .replace(', ', ',')
+        .split(',');
+    } else {
+      this.authors = [];
```
Comment (Danryg) [inline cremona/src/Book.ts:38]: Shouldn't authors = null in order to stay consistent with all the empty attributes.

File: cremona/src/Book.ts [hunk 2]
```diff
@@ -1,43 +1,58 @@
...
+    }
+    props['attributes'][1424] !== undefined // convert string of course codes to list
+      ? (this.courseCodes = props['attributes'][1424]['sv']
+          .replace(/ /g, '')
+          .split(','))
+      : (this.courseCodes = []);
```
Comment (Danryg) [inline cremona/src/Book.ts:44]: Same here

**Review by Danryg — CHANGES_REQUESTED** [review]
Generally looks good, just some ? about how we should manage empty attributes

File: cremona/src/Book.ts (hunk 1 above)
Comment (emilsvennesson) [reply cremona/src/Book.ts:38]: Not sure here: @EliasFalk?

Comment (EliasFalk) [reply cremona/src/Book.ts:38]: I think I agree with @Danryg on this one. Otherwise strings should probably be empty strings and numbers be something like 0 in order to stay consistent and I think that's going to be more problematic. Not sure whether it would be possible or beneficial in this case but making the attributes for the class/interface for a book optional, for example `{authors?: Array}`, could also be a solution since it would either be an array or "undefined" and thus staying consistent that way.

**Comment by emilsvennesson** [comment]
Thoughts about this instead? @EliasFalk @Danryg

**Comment by EliasFalk** [comment]
### LGTM
This looks good to me!!!
